# Generated by Django 5.2.4 on 2025-08-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DentsInspector.damagetype')),
                ('l', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DentsInspector.location')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DentsInspector.part')),
                ('s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DentsInspector.severity')),
            ],
            options={
                'unique_together': {('p', 'l', 'd', 's')},
            },
        ),
    ]
