# Generated by Django 5.2.4 on 2025-08-06 08:11
# DentsInspector/migrations/000X_auto_YYYYMMDD_HHMM.py (replace X, YYYYMMDD_HHMM with actual values)

from django.db import migrations


def populate_part_data(apps, schema_editor):
    """
    Populates the Part model with initial data.
    """
    Part = apps.get_model('DentsInspector', 'Part')

    parts_to_create = [
        {'id': 0, 'part': 'car'},
        {'id': 1, 'part': 'wheel'},
        {'id': 2, 'part': 'bumper'},
        {'id': 3, 'part': 'mirror'},
        {'id': 5, 'part': 'headlight'},
        {'id': 6, 'part': 'rear-light'},
        {'id': 7, 'part': 'fog-light'},
        {'id': 8, 'part': 'brake-light'},
        {'id': 9, 'part': 'grille'},
        {'id': 10, 'part': 'windshield'},
        {'id': 11, 'part': 'side-window'},
        {'id': 12, 'part': 'door-window'},
        {'id': 13, 'part': 'quarter-glass'},
        {'id': 15, 'part': 'hood'},
        {'id': 16, 'part': 'door'},
        {'id': 17, 'part': 'threshold'},
        {'id': 20, 'part': 'pillar'},
        {'id': 22, 'part': 'wing'},
        {'id': 23, 'part': 'trunk-door'},
        {'id': 24, 'part': 'sliding-door'},
        {'id': 27, 'part': 'roof'},
        {'id': 28, 'part': 'vent-glass'},
        {'id': 31, 'part': 'side-step'},
        {'id': 32, 'part': 'tow-hitch'},
        {'id': 33, 'part': 'spoiler'},
        {'id': 37, 'part': 'lower-valance'},
        {'id': 42, 'part': 'underbody'},
        {'id': 43, 'part': 'car-interior'},
        {'id': 44, 'part': 'center-console'},
        {'id': 45, 'part': 'pillar-interior'},
        {'id': 46, 'part': 'seat-belt'},
        {'id': 52, 'part': 'seat'},
        {'id': 53, 'part': 'floor-mat'},
        {'id': 61, 'part': 'convertible-top'},
        {'id': 62, 'part': 'dashboard'},
        {'id': 66, 'part': 'glove-box'},
        {'id': 68, 'part': 'steering-wheel'},
        {'id': 71, 'part': 'instrument-panel'},
        {'id': 72, 'part': 'door-card'},
        {'id': 75, 'part': 'rearview-mirror'},
        {'id': 79, 'part': 'spare-wheel'},
        {'id': 84, 'part': 'trunk-shelf'},
        {'id': 91, 'part': 'headliner'},
        {'id': 98, 'part': 'trunk-floor'},
        {'id': 102, 'part': 'transmission'},
        {'id': 104, 'part': 'starting-system'},
        {'id': 105, 'part': 'suspension'},
        {'id': 112, 'part': 'warning-abs'},
        {'id': 114, 'part': 'engine'},
        {'id': 115, 'part': 'warning-tpms'},
        {'id': 116, 'part': 'warning-tcs'},
        {'id': 117, 'part': 'warning-oil'},
        {'id': 118, 'part': 'inspection-sticker'},
        {'id': 119, 'part': 'registration'},
        {'id': 122, 'part': 'driver-assist-systems'},
        {'id': 125, 'part': 'wheel-arch'},
        {'id': 126, 'part': 'keys'},
        {'id': 127, 'part': 'tools'},
        {'id': 129, 'part': 'cargo-cover'},
        {'id': 130, 'part': 'tyre'},
        {'id': 134, 'part': 'seat-heating'},
        {'id': 135, 'part': 'window-heating'},
        {'id': 139, 'part': 'multimedia-control-unit'},
        {'id': 142, 'part': 'service-history'},
        {'id': 144, 'part': 'air-conditioning'},
        {'id': 149, 'part': 'carpet'},
        {'id': 168, 'part': 'overhead-console'},
        {'id': 175, 'part': 'truck-bed'},
        {'id': 184, 'part': 'radiator-support'},
        {'id': 187, 'part': 'engine-splash-shield'},
        {'id': 191, 'part': 'cooling-system'},
        {'id': 213, 'part': 'warning-steering'},
        {'id': 214, 'part': 'warning-service'},
        {'id': 215, 'part': 'threshold-interior'},
        {'id': 217, 'part': 'washer-system'},
        {'id': 228, 'part': 'parking-brake-system'},
        {'id': 230, 'part': 'rear-panel'},
        {'id': 233, 'part': 'trunk-door-card'},
        {'id': 234, 'part': 'warning-airbag'},
        {'id': 235, 'part': 'warning-battery'},
        {'id': 236, 'part': 'warning-brakes'},
        {'id': 237, 'part': 'warning-engine'},
        {'id': 239, 'part': 'engine-compartment'},
        {'id': 241, 'part': 'tailgate-strut'},
        {'id': 244, 'part': 'air-intake-system'},
        {'id': 245, 'part': 'electrical-system'},
        {'id': 246, 'part': 'fluids-system'},
    ]

    for data in parts_to_create:
        Part.objects.create(**data)


def reverse_part_data(apps, schema_editor):
    """
    Deletes the Part data created by populate_part_data.
    """
    Part = apps.get_model('DentsInspector', 'Part')
    # Delete all parts that were created by this migration
    # You could also delete based on the 'id's if you prefer
    Part.objects.filter(id__in=[
        0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 20, 22, 23, 24,
        27, 28, 31, 32, 33, 37, 42, 43, 44, 45, 46, 52, 53, 61, 62, 66, 68, 71,
        72, 75, 79, 84, 91, 98, 102, 104, 105, 112, 114, 115, 116, 117, 118,
        119, 122, 125, 126, 127, 129, 130, 134, 135, 139, 142, 144, 149, 168,
        175, 184, 187, 191, 213, 214, 215, 217, 228, 230, 233, 234, 235, 236,
        237, 239, 241, 244, 245, 246
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('DentsInspector', '0001_initial'),  # Ensure this points to your latest schema migration
    ]

    operations = [
        migrations.RunPython(populate_part_data, reverse_part_data),
    ]