# DentsInspector/migrations/000X_auto_YYYYMMDD_HHMM.py (replace X, YYYYMMDD_HHMM with actual values)

from django.db import migrations


def populate_damage_type_data(apps, schema_editor):
    """
    Populates the DamageType model with initial data.
    """
    DamageType = apps.get_model('DentsInspector', 'DamageType')

    # New data parsed from the provided string
    damage_types_to_create = [
        {'id': 1, 'type': 'scratch'},
        {'id': 2, 'type': 'dent'},
        {'id': 3, 'type': 'chip-and-crack'},
        {'id': 4, 'type': 'missing'},
        {'id': 5, 'type': 'dirt'},
        {'id': 6, 'type': 'broken'},
        {'id': 8, 'type': 'patched'},
        {'id': 9, 'type': 'torn-off'},
        {'id': 12, 'type': 'paintwork-issues'},
        {'id': 13, 'type': 'scratch-and-dent'},
        {'id': 14, 'type': 'sand-damage'},
        {'id': 17, 'type': 'rust'},
        {'id': 20, 'type': 'odor'},
        {'id': 22, 'type': 'mechanical-issues'},
        {'id': 28, 'type': 'warning-light-on'},
        {'id': 30, 'type': 'previous-accident'},
        {'id': 35, 'type': 'cut'},
        {'id': 36, 'type': 'gouged'},
        {'id': 37, 'type': 'hole'},
        {'id': 40, 'type': 'stain'},
        {'id': 41, 'type': 'worn'},
        {'id': 42, 'type': 'inoperable'},
        {'id': 46, 'type': 'burn'},
        {'id': 48, 'type': 'battery-damaged'},
        {'id': 49, 'type': 'sidewall-bulge'},
        {'id': 50, 'type': 'mismatched-size'},
        {'id': 51, 'type': 'mismatched-brand'},
        {'id': 52, 'type': 'aftermarket'},
        {'id': 53, 'type': 'flat'},
        {'id': 54, 'type': 'cupping'},
        {'id': 55, 'type': 'mismatched-type'},
        {'id': 57, 'type': 'hail-damage'},
        {'id': 58, 'type': 'sticker-damage'},
        {'id': 61, 'type': 'altered'},
        {'id': 62, 'type': 'water-damage'},
        {'id': 64, 'type': 'noise'},
        {'id': 66, 'type': 'leak'},
        {'id': 73, 'type': 'commercial-usage'},
        {'id': 74, 'type': 'abuse'},
        {'id': 76, 'type': 'overheat'},
        {'id': 77, 'type': 'cap-missing'},
        {'id': 78, 'type': 'fuel-flap-damaged'},
        {'id': 79, 'type': 'fuel-flap-missing'},
        {'id': 80, 'type': 'handle-damaged'},
        {'id': 81, 'type': 'handle-missing'},
        {'id': 83, 'type': 'backup-camera-missing'},
        {'id': 85, 'type': 'glass-missing'},
        {'id': 86, 'type': 'glass-damaged'},
        {'id': 87, 'type': 'radio-antenna-damaged'},
        {'id': 88, 'type': 'radio-antenna-missing'},
        {'id': 89, 'type': 'rubber-seal-damaged'},
        {'id': 90, 'type': 'rubber-seal-missing'},
        {'id': 91, 'type': 'sensor-parking-damaged'},
        {'id': 92, 'type': 'sensor-parking-missing'},
        {'id': 93, 'type': 'sunroof-damaged'},
        {'id': 94, 'type': 'sunroof-missing'},
        {'id': 95, 'type': 'symbol-damaged'},
        {'id': 96, 'type': 'symbol-missing'},
        {'id': 97, 'type': 'trim-damaged'},
        {'id': 98, 'type': 'trim-missing'},
        {'id': 99, 'type': 'nut-missing'},
        {'id': 100, 'type': 'cover-damaged'},
        {'id': 101, 'type': 'cover-missing'},
        {'id': 102, 'type': 'collision-radar-damaged'},
        {'id': 103, 'type': 'collision-radar-missing'},
        {'id': 104, 'type': 'inner-rear-light-damaged'},
        {'id': 105, 'type': 'inner-rear-light-missing'},
        {'id': 107, 'type': 'license-plate-holder-missing'},
        {'id': 110, 'type': 'rail-damaged'},
        {'id': 111, 'type': 'rail-missing'},
        {'id': 112, 'type': 'tint-aftermarket'},
        {'id': 113, 'type': 'tint-damaged'},
        {'id': 116, 'type': 'wiper-inoperable'},
        {'id': 117, 'type': 'wiper-damaged'},
        {'id': 118, 'type': 'wiper-missing'},
        {'id': 119, 'type': 'air-vent-grille-damaged'},
        {'id': 120, 'type': 'air-vent-grille-missing'},
        {'id': 121, 'type': 'armrest-damaged'},
        {'id': 122, 'type': 'armrest-missing'},
        {'id': 123, 'type': 'controls-damaged'},
        {'id': 124, 'type': 'controls-missing'},
        {'id': 125, 'type': 'cup-holder-damaged'},
        {'id': 126, 'type': 'cup-holder-missing'},
        {'id': 127, 'type': 'hazard-switch-damaged'},
        {'id': 128, 'type': 'hazard-switch-missing'},
        {'id': 129, 'type': 'headrest-damaged'},
        {'id': 130, 'type': 'headrest-missing'},
        {'id': 131, 'type': 'horn-switch-damaged'},
        {'id': 132, 'type': 'horn-switch-missing'},
        {'id': 133, 'type': 'interior-light-damaged'},
        {'id': 134, 'type': 'interior-light-missing'},
        {'id': 135, 'type': 'multifunction-switch-damaged'},
        {'id': 136, 'type': 'multifunction-switch-missing'},
        {'id': 137, 'type': 'multimedia-display-damaged'},
        {'id': 138, 'type': 'multimedia-display-missing'},
        {'id': 139, 'type': 'parking-brake-damaged'},
        {'id': 140, 'type': 'parking-brake-missing'},
        {'id': 141, 'type': 'shift-boot-damaged'},
        {'id': 142, 'type': 'shift-boot-missing'},
        {'id': 143, 'type': 'shift-knob-damaged'},
        {'id': 144, 'type': 'shift-knob-missing'},
        {'id': 145, 'type': 'shift-panel-damaged'},
        {'id': 146, 'type': 'shift-panel-missing'},
        {'id': 147, 'type': 'speaker-damaged'},
        {'id': 148, 'type': 'speaker-missing'},
        {'id': 149, 'type': 'start-button-damaged'},
        {'id': 150, 'type': 'start-button-missing'},
        {'id': 151, 'type': 'window-switch-damaged'},
        {'id': 152, 'type': 'window-switch-missing'},
        {'id': 153, 'type': 'turn-signal-damaged'},
        {'id': 154, 'type': 'turn-signal-missing'},
        {'id': 155, 'type': 'label-damaged'},
        {'id': 156, 'type': 'label-missing'},
        {'id': 157, 'type': 'sunvisor-damaged'},
        {'id': 158, 'type': 'sunvisor-missing'},
        {'id': 159, 'type': 'backup-camera-inoperable'},
        {'id': 161, 'type': 'adblue-degraded'},
        {'id': 162, 'type': 'adblue-misfilled'},
        {'id': 163, 'type': 'adblue-reservoir-damaged'},
        {'id': 164, 'type': 'air-filter-box-damaged'},
        {'id': 165, 'type': 'air-flow-sensor-damaged'},
        {'id': 166, 'type': 'air-intake-manifold-damaged'},
        {'id': 167, 'type': 'airbag-damage'},
        {'id': 168, 'type': 'alternator-damaged'},
        {'id': 169, 'type': 'battery-missing'},
        {'id': 170, 'type': 'brake-fluid-degraded'},
        {'id': 171, 'type': 'brake-fluid-misfilled'},
        {'id': 172, 'type': 'brake-fluid-reservoir-damaged'},
        {'id': 173, 'type': 'bull-bar-damaged'},
        {'id': 174, 'type': 'bull-bar-missing'},
        {'id': 175, 'type': 'camera-damaged'},
        {'id': 176, 'type': 'camera-missing'},
        {'id': 177, 'type': 'cap-damaged'},
        {'id': 178, 'type': 'coolant-degraded'},
        {'id': 179, 'type': 'coolant-misfilled'},
        {'id': 180, 'type': 'coolant-reservoir-damaged'},
        {'id': 181, 'type': 'drive-belt-damaged'},
        {'id': 182, 'type': 'ecu-damaged'},
        {'id': 183, 'type': 'ecu-missing'},
        {'id': 184, 'type': 'evaporator-damaged'},
        {'id': 185, 'type': 'exhaust-damaged'},
        {'id': 186, 'type': 'exhaust-missing'},
        {'id': 187, 'type': 'fuse-box-damaged'},
        {'id': 188, 'type': 'hood-insulation-damaged'},
        {'id': 189, 'type': 'hood-latch-damaged'},
        {'id': 190, 'type': 'hood-strut-damaged'},
        {'id': 191, 'type': 'hose-damaged'},
        {'id': 192, 'type': 'hose-missing'},
        {'id': 193, 'type': 'intercooler-damaged'},
        {'id': 194, 'type': 'license-plate-holder-damaged'},
        {'id': 195, 'type': 'lock-damaged'},
        {'id': 196, 'type': 'lower-grille-damaged'},
        {'id': 197, 'type': 'lower-grille-missing'},
        {'id': 198, 'type': 'mud-flap-damaged'},
        {'id': 199, 'type': 'mud-flap-missing'},
        {'id': 200, 'type': 'panoramic-roof-damaged'},
        {'id': 201, 'type': 'panoramic-roof-missing'},
        {'id': 202, 'type': 'radiator-damaged'},
        {'id': 203, 'type': 'radiator-fan-damaged'},
        {'id': 204, 'type': 'shield-damaged'},
        {'id': 205, 'type': 'steering-fluid-degraded'},
        {'id': 206, 'type': 'steering-fluid-misfilled'},
        {'id': 207, 'type': 'steering-fluid-reservoir-damaged'},
        {'id': 209, 'type': 'upper-grille-damaged'},
        {'id': 210, 'type': 'upper-grille-missing'},
        {'id': 211, 'type': 'washer-fluid-degraded'},
        {'id': 212, 'type': 'washer-fluid-misfilled'},
        {'id': 213, 'type': 'washer-fluid-reservoir-damaged'},
        {'id': 214, 'type': 'wiring-damaged'},
        {'id': 215, 'type': 'drive-belt-missing'},
        {'id': 216, 'type': 'motor-oil-degraded'},
        {'id': 217, 'type': 'motor-oil-misfilled'},
        {'id': 218, 'type': 'transmission-fluid-degraded'},
        {'id': 219, 'type': 'transmission-fluid-misfilled'},
        {'id': 220, 'type': 'brackets-damaged'},
        {'id': 221, 'type': 'reinforcement-bar-damaged'},
        {'id': 222, 'type': 'support-damaged'},
        {'id': 223, 'type': 'airbag-deployed'},
        {'id': 224, 'type': 'suspension-damaged'},
    ]

    for data in damage_types_to_create:
        # Using update_or_create to handle cases where IDs might already exist
        # This prevents errors if the migration is run multiple times or if some IDs are already present
        DamageType.objects.update_or_create(id=data['id'], defaults={'type': data['type']})


def reverse_damage_type_data(apps, schema_editor):
    """
    Deletes the DamageType data created by populate_damage_type_data.
    """
    DamageType = apps.get_model('DentsInspector', 'DamageType')
    # Delete all damage types that were created by this migration
    # Ensure this list matches the IDs from the populate_damage_type_data function
    DamageType.objects.filter(id__in=[
        1, 2, 3, 4, 5, 6, 8, 9, 12, 13, 14, 17, 20, 22, 28, 30, 35, 36, 37, 40,
        41, 42, 46, 48, 49, 50, 51, 52, 53, 54, 55, 57, 58, 61, 62, 64, 66, 73,
        74, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
        95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 107, 110, 111, 112,
        113, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
        172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185,
        186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199,
        200, 201, 202, 203, 204, 205, 206, 207, 209, 210, 211
    ]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('DentsInspector', '0003_populate_locations'),
        # Ensure this points to your latest schema migration (e.g., the Location data migration)
    ]

    operations = [
        migrations.RunPython(populate_damage_type_data, reverse_damage_type_data),
    ]
